language: node_js
node_js:
  - "8"

services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -a -f ./schema.sql
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres
  - node index.js &